name: Docker
on: [push]
jobs:
  libc23:
    name: Build & publish libc23
    runs-on: ubuntu-latest    
    steps:
      -  name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: giorgiopiatti/ctf-tools-libc23
          tag: latest #${{ steps.get_version.outputs.VERSION }}
          registry: docker.io
          dockerfile: lib23.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}$
  libc27:
    name: Build & publish libc27
    runs-on: ubuntu-latest    
    steps:
      -  name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: giorgiopiatti/ctf-tools-libc27
          tag: latest #${{ steps.get_version.outputs.VERSION }}
          registry: docker.io
          dockerfile: lib27.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  libc28:
    name: Build & publish libc28
    runs-on: ubuntu-latest    
    steps:
      -  name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: giorgiopiatti/ctf-tools-libc28
          tag: latest #${{ steps.get_version.outputs.VERSION }}
          registry: docker.io
          dockerfile: lib28.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  libc29:
    name: Build & publish libc29
    runs-on: ubuntu-latest    
    steps:
      -  name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: giorgiopiatti/ctf-tools-libc29
          tag: latest #${{ steps.get_version.outputs.VERSION }}
          registry: docker.io
          dockerfile: lib29.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}